1.- Importa las librerías Numpy para vectores y matricez y pandas para manipular y analizar datos
2.- Genera un arreglo "array1" del tamaño de los centroides resultantes
3.- Guarda en una variable la longitud de éste arreglo
4.- Se copia el arreglo "array1" como "array2"
5.- Guarda en una variable la longitud del "array2"
6.- Genera una lista vacía que servirá para la futura Matriz
7.- Para cada i que habita en el "array1", buscará cada j que habita en el "array2", anexando (append) el valor absoluto de la resta entre todas las combinaciones posibles entre i y j.Dando como resultado una lista de 1xlen(array1) = 36
8.- Mn será la Matriz que se forma de la lista M reacomodada, dando los elementos de M y el tamaño (longitudes de las matricez) deseadas.
9.- Imprime la Matrix y lo hace debajo de la línea, no enseguida.
10.- Imrpime un espacio y un brinco de línea
11.- Imprime el promedio de la Matriz
12.- Imprime el valor máximo de la Matrix
13.-




In [ ]:
import numpy as np
import pandas as pd


array1 = np.array([0, 0, 0, .5])
len_array1= len(array1)

array2 =array1
len_array2=(len(array2))

M = [ ]

for i in array1:
  for j in array2:
    M.append(np.absolute(i-j))


Mn = np.reshape(M, (len_array1,len_array2))
print('La matrix de disimilaridad es la siguiente: ', Mn, sep='\n')
print(' ', sep='\n')

print('El promedio de las distancias es: ', Mn.mean())
print(' ', sep='\n')

Mnn = np.max(Mn)
print('El valor más disímil es: ', Mnn)
print(' ', sep='\n')




result = np.where(Mn == np.amax(Mn))

print('Las coordenadas del valor más disimil son (renglón, columna, iniciando desde 0, no de 1): ', sep='\n')
listOfCordinates = list(zip(result[0], result[1]))
for cord in listOfCordinates:
        print(cord)



La matrix de disimilaridad es la siguiente: 
[[0.  0.  0.  0.5]
 [0.  0.  0.  0.5]
 [0.  0.  0.  0.5]
 [0.5 0.5 0.5 0. ]]
 
El promedio de las distancias es:  0.1875
 
El valor más disímil es:  0.5
 
Las coordenadas del valor más disimil son (renglón, columna, iniciando desde 0, no de 1): 
(0, 3)
(1, 3)
(2, 3)
(3, 0)
(3, 1)
(3, 2)


In [ ]:
import pandas as pd
import numpy as np

# Abrir el archivo de datos
with open('Book3.txt', 'r') as archivo:
          # Leer el contenido del archivo línea por línea
    filas = []
    for linea in archivo:
        numeros = [float(numero) for numero in linea.strip().split('	')]
        numeros1 = numeros
        len_numeros =len(numeros)
        len_numeros1 = len_numeros
        M = []
        for i in numeros:
           for j in numeros1:
              M.append(np.absolute(i-j))
        Mn = np.reshape(M, (len_numeros, len_numeros1))
        Mn_mean = np.mean(Mn)
        Mn_max= np.max(Mn)
        numeros.append(Mn_mean)
        numeros.append(Mn_max)
        filas.append(numeros)


        result = np.where(Mn == np.amax(Mn))
        listOfCordinates = list(zip(result[0], result[1]))
        for cord in listOfCordinates:
            print(cord)
        numeros.append(cord)
        print(Mn)
        print(numeros)


with open('PE1_mediadetodaslasdiferencias_valormasdisimil_mascoordenada.txt', 'w') as archivo_nuevo:
    for fila in filas:
        linea = ' '.join(str(numero) for numero in fila)
        linea += f' {" "}\n'
        archivo_nuevo.write(linea)

(0, 9)
(0, 10)
(0, 11)
(0, 21)
(0, 22)
(0, 23)
(1, 9)
(1, 10)
(1, 11)
(1, 21)
(1, 22)
(1, 23)
(2, 9)
(2, 10)
(2, 11)
(2, 21)
(2, 22)
(2, 23)
(3, 9)
(3, 10)
(3, 11)
(3, 21)
(3, 22)
(3, 23)
(4, 9)
(4, 10)
(4, 11)
(4, 21)
(4, 22)
(4, 23)
(5, 9)
(5, 10)
(5, 11)
(5, 21)
(5, 22)
(5, 23)
(6, 9)
(6, 10)
(6, 11)
(6, 21)
(6, 22)
(6, 23)
(9, 0)
(9, 1)
(9, 2)
(9, 3)
(9, 4)
(9, 5)
(9, 6)
(9, 12)
(9, 13)
(9, 14)
(9, 15)
(9, 16)
(9, 17)
(9, 18)
(10, 0)
(10, 1)
(10, 2)
(10, 3)
(10, 4)
(10, 5)
(10, 6)
(10, 12)
(10, 13)
(10, 14)
(10, 15)
(10, 16)
(10, 17)
(10, 18)
(11, 0)
(11, 1)
(11, 2)
(11, 3)
(11, 4)
(11, 5)
(11, 6)
(11, 12)
(11, 13)
(11, 14)
(11, 15)
(11, 16)
(11, 17)
(11, 18)
(12, 9)
(12, 10)
(12, 11)
(12, 21)
(12, 22)
(12, 23)
(13, 9)
(13, 10)
(13, 11)
(13, 21)
(13, 22)
(13, 23)
(14, 9)
(14, 10)
(14, 11)
(14, 21)
(14, 22)
(14, 23)
(15, 9)
(15, 10)
(15, 11)
(15, 21)
(15, 22)
(15, 23)
(16, 9)
(16, 10)
(16, 11)
(16, 21)
(16, 22)
(16, 23)
(17, 9)
(17, 10)
(17, 11)
(17, 21)
(17, 22)
(17, 23)
(18, 9)
(1

In [ ]:
import pandas as pd
import numpy as np

# Abrir el archivo de datos
with open('PE1(p).txt', 'r') as archivo:
          # Leer el contenido del archivo línea por línea
    filas = []
    for line in archivo:
        numeros = [float(numero) for numero in line.strip().split('  ')]
        numeros1 = numeros
        len_numeros =len(numeros)
        len_numeros1 = len_numeros
        M = []
        for i in numeros:
           for j in numeros1:
              M.append(np.absolute(i-j))
        Mn = np.reshape(M, (len_numeros, len_numeros1))
        Mn_mean = np.mean(Mn)
        Mn_max= np.max(Mn)
        numeros.append(Mn_mean)
        numeros.append(Mn_max)
        filas.append(numeros)

        print(Mn)
        #print(numeros)

#Escribir los números originales y los promedios en un nuevo archivo
with open('promedios.txt', 'w') as archivo_nuevo:
    for fila in filas:
        linea = ' '.join(str(numero) for numero in fila)
        linea += f' {" "}\n'
        archivo_nuevo.write(linea)


Mnn = np.max(Mn)

print(Mnn)



result = np.where(Mn == np.amax(Mn))

#print(result)

print('Las coordenadas del valor más disimil son (renglón, columna, iniciando desde 0, no de 1): ', sep='\n')
listOfCordinates = list(zip(result[0], result[1]))
for cord in listOfCordinates:
        print(cord)

[[ 0. 44.]
 [44.  0.]]
[[0.         0.         0.04993758 0.00374532 0.         0.00187266]
 [0.         0.         0.04993758 0.00374532 0.         0.00187266]
 [0.04993758 0.04993758 0.         0.04619226 0.04993758 0.04806492]
 [0.00374532 0.00374532 0.04619226 0.         0.00374532 0.00187266]
 [0.         0.         0.04993758 0.00374532 0.         0.00187266]
 [0.00187266 0.00187266 0.04806492 0.00187266 0.00187266 0.        ]]
[[0.         0.         0.01897983 0.         0.         0.        ]
 [0.         0.         0.01897983 0.         0.         0.        ]
 [0.01897983 0.01897983 0.         0.01897983 0.01897983 0.01897983]
 [0.         0.         0.01897983 0.         0.         0.        ]
 [0.         0.         0.01897983 0.         0.         0.        ]
 [0.         0.         0.01897983 0.         0.         0.        ]]
[[0.         0.         0.04350528 0.         0.         0.        ]
 [0.         0.         0.04350528 0.         0.         0.        ]
 [0.04350

In [ ]:
def Average(lst):
    return sum(lst) / len(lst)

with open("/content/prueba.txt", 'r') as f:
    df = f.readline()
    #print(df)
    num = list(map(float, df.split()))
    average = Average(num)
    average_str =str(average)
    print(num)
    print(type(num))
    print(average)
    print(type(average))


with open("/content/prueba_a.txt", 'w') as f:
    lista =[]
    lista.append(df)
    lista.append(average)
    lista_str = str(lista)
    print(lista_str)
    #print(lista)
    f.write(lista_str)
    #f.write(average_str)





FileNotFoundError: ignored

In [ ]:
line = "ABCD"
with open('text.txt', 'r+') as file:
 file_data = file.read()
 file.seek(0, 0)
 file.write(line + '\n' + file_data)

FileNotFoundError: ignored